//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using beta.ViewModels;

namespace beta.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Servers : global::System.Configuration.ApplicationSettingsBase {
        
        private static Servers defaultInstance = ((Servers)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Servers())));
        
        public static Servers Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public ClientEnvironment[] Environments {
            get {
                return ((ClientEnvironment[])(this["Environments"]));
            }
            set {
                this["Environments"] = value;
            }
        }
    }
}
