//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ethereal.FAF.UI.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //[global::System.Configuration.DefaultSettingValueAttribute("{\"access_token\":\"eyJhbGciOiJSUzI1NiIsImtpZCI6InB1YmxpYzo5N2U2ZmQxMy0zNDcxLTQ4ZDgt" +
        //    "YTA3OC1jYzVhMWIzNTZiMzYiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOltdLCJjbGllbnRfaWQiOiJldGhlc" +
        //    "mVhbC1mYWYtY2xpZW50IiwiZXhwIjoxNjYxNjA4NjgyLCJleHQiOnsicm9sZXMiOlsiVVNFUiJdLCJ1c" +
        //    "2VybmFtZSI6IkV0ZXJuYWwtIn0sImlhdCI6MTY2MTYwNTA4MiwiaXNzIjoiaHR0cHM6Ly9oeWRyYS5mY" +
        //    "WZvcmV2ZXIuY29tLyIsImp0aSI6IjA4NWU0NjUyLTYyNjgtNDA1MS1iY2Q3LTlmNmQ5NzQyZmFiYiIsI" +
        //    "m5iZiI6MTY2MTYwNTA4Miwic2NwIjpbIm9wZW5pZCIsIm9mZmxpbmUiLCJwdWJsaWNfcHJvZmlsZSIsI" +
        //    "mxvYmJ5IiwidXBsb2FkX21hcCIsInVwbG9hZF9tb2QiXSwic3ViIjoiMzAyMTc2In0.GPqxg95RJYpQI" +
        //    "TFctxJoJOF5F_zxqOO3e0_GLb0oiNHdCaqgy26N2fb2bTOdb8ptOUTGd0IjpJeoINrzUuChQptbold0X" +
        //    "EIiifaANR4BkCHiXEPx6NwyOolqyeH-9SfLVdtRESfeuvpUrMEz0UAV7Rx8gmMyd8A5ZLz0Ya4Kh3vhw" +
        //    "3bzeErihI--No3iJy3S_cv6CGVGdwR9nrrNlzPhR3LOq3j_0vtN5ElxGNY4ghWdehHGguJBRjfIjmk4j" +
        //    "WN6ZmhK2cNw3vDKgoTexD_HrgEcTLvRsWPfVkRhzt_MK9MjDURww7sCAnLQtGM_fhMFAc86uKk3ymilU" +
        //    "LzqPMS5q2swxG78fjB8ZwQDDBPy3LYINHGZreejicQNh3dOJdCSrTjEGmBLVhX9CHy-A32GeAMzdatUN" +
        //    "obJTsePSx6_uOfljz849VThHTdbPR4VgTho_H15gP0qOsDp24kD6P3HULhanqMfXq6cy2kBzXr1YUlCa" +
        //    "_qQ13U-bE2HdSm_RKNHhCo7V7PE2hKZuVKIR93vtm5o460lq3eTToLmhyE5ivYGSX8k4bEvCtPcmdrz4" +
        //    "nXsvKJ5rS9UZ1Pqpg3zyoFlf67J4dO0IYevNy4ezuLfPpECV8rFmY9LEGp4-MjfKp2WjgecAMwB5hLlf" +
        //    "qUfOK5igDbf9JQzgHv7-qXfxtWxsGY\",\"expires_in\":3599,\"id_token\":\"eyJhbGciOiJSUzI1Ni" +
        //    "IsImtpZCI6InB1YmxpYzo3NDNmZWQ1Ny1lN2NkLTQ5NjYtYTA0ZC1jNGNlZGNhZjFhMDQiLCJ0eXAiOi" +
        //    "JKV1QifQ.eyJhdF9oYXNoIjoiUmZHQVR6ZE5KT09kdF9zQVBwT2VpdyIsImF1ZCI6WyJldGhlcmVhbC1" +
        //    "mYWYtY2xpZW50Il0sImF1dGhfdGltZSI6MTY2MTYwNTA4MCwiZXhwIjoxNjYxNjA4NjgyLCJpYXQiOjE" +
        //    "2NjE2MDUwODIsImlzcyI6Imh0dHBzOi8vaHlkcmEuZmFmb3JldmVyLmNvbS8iLCJqdGkiOiIyNTc0Zjd" +
        //    "iYS0wMmQ0LTRiMzctOGNkMS03YWM5MjYzYjc3ZWIiLCJyYXQiOjE2NjE2MDUwNzgsInJvbGVzIjpbIlV" +
        //    "TRVIiXSwic2lkIjoiZTE0MDRmZjAtMjllYS00ZTgzLWJjZjYtMDc3Mjg4MzRkMDVjIiwic3ViIjoiMzA" +
        //    "yMTc2IiwidXNlcm5hbWUiOiJFdGVybmFsLSJ9.0rMEprkRUSTM8vgLktG38MbiEcP85JvgqPB-MdbM_h" +
        //    "blY_dq0m0SxF94v0AXH_kWzvqaWwkaz7XrroM2fO4PRgTHXfuuSlzosng6YUbvJed7W8NBlOg43evHB1" +
        //    "FoN_by3PAra4Q3WfmtIWPqvlXdkJLxI3RsEHTi_lADWSy5IyqHmqBlgnUFRposGRmi5UA9_V-ozI2dVr" +
        //    "hOT64TogynGvXZLbbfbIaRfPHeSU4ZqGIUbAtUiWLcmb_pOcf2qguv5padT8N3-5SykJssTGPJstiT9q" +
        //    "xBBrL6HajIcYGaWZYlAQw4QP118b7JtRcb3SXfPNJAvaAeQX4h5HiO6Jzkv8d06NDxR_w26-43RgmNDD" +
        //    "OU0DoFgnkYviH1Ldrg2Md2scVOsMf4JVNA0OSLdUZw6ZEDlwnqN6ub9iTujrqzI5ReNTP_KG3faXkZO3" +
        //    "D5qVsFfrH8VINJDM7NSA3kIpl36LCtCXOnzwlnUZasRSBM9NOLlCCXyAbA6IoTomwA7Q1NJhMxqYajuG" +
        //    "vjcac8x5sBeIu43Ay2qxYP4lNQ3ZC4NJNXiAq-BEUWXTt57Z9bXxfBUOejIeiqaDFv03VMDxKPpuFDqP" +
        //    "Bo5r-PIseYq2Tdr5qU7dCG4ayqS4690bE7h3BZ3ZXWWyP44tyq4bc_lgsnUrKFFiZjU4NnZv6Of_TQs6" +
        //    "o\",\"refresh_token\":\"BqGyRdUdEKhl8YOcDaKJ38SQUzXNCzXqBRVtMlkfInk.3S-Ta_9Ymxq-5lco" +
        //    "ybjzlUEmNPlHgtslLmd86FZ9qz8\",\"token_type\":\"bearer\",\"scope\":\"openid offline publi" +
        //    "c_profile lobby upload_map upload_mod\",\"created\":\"2022-08-27T17:58:01.2922152+05" +
        //    ":00\"}")]
        public global::Ethereal.FAF.UI.Client.Infrastructure.OAuth.TokenBearer Token {
            get {
                return ((global::Ethereal.FAF.UI.Client.Infrastructure.OAuth.TokenBearer)(this["Token"]));
            }
            set {
                this["Token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
